### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by normanstanleyspencer** [jnimmo/hass-dmx#10]
First of all, thanks very much for this.

I am trying to install the package on hass.io and I get the following error:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 242, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/light/__init__.py", line 506, in state_attributes
    if supported_features & SUPPORT_COLOR_TEMP:
TypeError: unsupported operand type(s) for &: 'tuple' and 'int'
```

Any ideas?  Thanks

**Comment by normanstanleyspencer** [comment]
This was only for the type = 'switch' - when type = 'dimmer', the error does not present itself.

**Comment by jnimmo** [comment]
Oops I obviously didn't test that one, should be fixed now (note, module renamed from artnet to dmx
Cheers
