### ISSUE TITLE
DRGB

### ISSUE THREAD

**Issue by mattjbailey** [jnimmo/hass-dmx#32]
Anytime I set my config type to RGB, everything works. When I set the config type to DRGB, no lights show up in home assistant and I get this error:

Logger: homeassistant.core
Source: custom_components/dmx/light.py:479
First occurred: 8:48:31 AM (1 occurrences)
Last logged: 8:48:31 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 288, in async_add_entities
    for entity in new_entities
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 285, in <listcomp>
    self._async_add_entity(  # type: ignore
  File "/config/custom_components/dmx/light.py", line 163, in <genexpr>
    lights = (DMXLight(light, dmx_gateway, send_levels_on_startup, default_light_type) for light in
  File "/config/custom_components/dmx/light.py", line 214, in __init__
    send_immediately)
  File "/config/custom_components/dmx/light.py", line 494, in set_channels
    self.send()
  File "/config/custom_components/dmx/light.py", line 479, in send
    packet.extend(self._channels)
TypeError: 'float' object cannot be interpreted as an integer

My Config:
`  - platform: dmx `
`    host: 192.168.2.125 #House DMX Controller (eDMX King)`
`    port: 6454`
`    dmx_channels: 512`
`    default_level: 0`
`    universe: 0` 
`   devices:`
`      - channel: 1`
`        name: Gazebo Light 1`
`        type: drgb`

**Comment by mattjbailey** [comment]
I figured out the issue. The DMX king needed to be in the same subnet as HA. Otherwise it was causing issues like this.
