### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by ruth-connect** [jnimmo/hass-dmx#37]
2020-07-21 22:48:24 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/dmx/light.py", line 538, in set_channels_async
    self.send()
  File "/config/custom_components/dmx/light.py", line 493, in send
    packet.extend(self._channels)
TypeError: 'float' object cannot be interpreted as an integer

**Comment by ruth-connect** [comment]
Fixed this in this pull request - https://github.com/jnimmo/hass-dmx/pull/38
